Repository Xuechunqiu/CMPUT404-project-socialdistribution, pull requests merged in 2021-03, with the labels that each got.

#107 Modify UI and logic in publicposts
  backend/socialdist/urls.py
  frontend/src/components/Home/index.js
  frontend/src/components/Inbox/index.js
  frontend/src/components/LoginComp/index.js
  frontend/src/components/PostDisplay/index.js
  frontend/src/components/Profile/index.js
  frontend/src/components/PublicAndMyPost/index.js
  frontend/src/components/Signup/index.js
  frontend/src/static/images/background.png
Labels: enhancement

#108 Support JWT token authentication + Http basic authentication now
  .gitignore
  backend/presentation/Viewsets/author_view.py
  backend/presentation/views.py
  backend/socialdist/settings.py
  frontend/src/components/Friends/index.js
  frontend/src/components/InboxRequest/index.js
  frontend/src/components/Signup/index.js
  frontend/src/requests/requestAuthor.js
  frontend/src/requests/requestComment.js
  frontend/src/requests/requestFriendRequest.js
  frontend/src/requests/requestFriends.js
  frontend/src/requests/requestPost.js
  misc/Deploy/settings.py
Labels: app, bugfix

#112 Support for dedicated authentication user account.
  backend/presentation/Serializers/__init__.py
  backend/presentation/Serializers/usermod_serializer.py
  backend/presentation/Viewsets/author_view.py
  backend/presentation/admin.py
  backend/presentation/models.py
  backend/presentation/utils.py
  backend/presentation/views.py
  backend/socialdist/settings.py
  backend/socialdist/urls.py
  frontend/src/components/LoginComp/index.js
  frontend/src/requests/requestAuthor.js
  misc/Deploy/settings.py
Labels: app, enhancement

#118 Add API documents.
  index.html
Labels: documentation

#117 Update model datetimefield and request UI
  backend/presentation/Viewsets/comment_view.py
  backend/presentation/Viewsets/post_view.py
  backend/presentation/models.py
  backend/socialdist/settings.py
  backend/socialdist/urls.py
  frontend/src/App.js
  frontend/src/components/CommentArea/index.js
  frontend/src/components/Friends/index.js
  frontend/src/components/Home/index.js
  frontend/src/components/Inbox/index.js
  frontend/src/components/InboxPost/index.js
  frontend/src/components/InboxRequest/index.js
  frontend/src/components/LoginComp/index.js
  frontend/src/components/Post/index.js
  frontend/src/components/PostDisplay/index.js
  frontend/src/components/Profile/index.js
  frontend/src/components/ProfileChange/index.js
  frontend/src/components/PublicAndMyPost/index.js
  frontend/src/components/SingleRequest/index.js
  frontend/src/index.css
  frontend/src/static/images/bg1.png
  frontend/src/static/images/bg2.jpg
  misc/Deploy/settings.py
Labels: bugfix, enhancement

#129 Environment variable supported.
  frontend/src/requests/URL.js
  misc/Deploy/URL.js
  misc/README.md
  misc/createsu.sh
  misc/deploy.sh
  misc/env.py
  misc/gen.py
  misc/predeploy.sh
Labels: app, enhancement
